// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// first_nonna
unsigned long first_nonna(NumericVector v);
RcppExport SEXP qlib_first_nonna(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    __result = Rcpp::wrap(first_nonna(v));
    return __result;
END_RCPP
}
