# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return the index of the first non-NA value
#'
#' @param v numeric vector
#' @return position of the first non-NA value. Return \code{length(v)+1} if the array only contains NAs.
#'
#' @export
first_nonna <- function(v) {
    .Call('qlib_first_nonna', PACKAGE = 'qlib', v)
}

